# Generated by Django 3.2 on 2022-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='certificate',
            field=models.CharField(max_length=512, null=True, verbose_name='certificate'),
        ),
    ]
