# Generated by Django 3.2 on 2022-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_filmwork_certificate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['film_work_id'], name='genre_film__film_wo_74db5b_idx'),
        ),
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['genre_id'], name='genre_film__genre_i_8cb997_idx'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['film_work_id'], name='person_film_film_wo_381720_idx'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['person_id'], name='person_film_person__a20545_idx'),
        ),
    ]
